#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 1 ]; then
    set -x
fi
set -eu
set -o pipefail

case "${REG_METHOD:-}" in
    rmt)
	RMT_IP_ADDR=${RMT_IP_ADDR:-192.168.0.1}
	cd /etc/pki/trust/anchors/
	wget https://$RMT_IP_ADDR/rmt.crt --no-check-certificate
	update-ca-certificates
	cd /tmp/
	RMT_SERVER=${RMT_SERVER:-rmt.local}
	RMT_CERT_FINGERPRINT=${RMT_CERT_FINGERPRINT:-AA:AA:AA}
	echo "$RMT_IP_ADDR $RMT_SERVER" >> /etc/hosts
	cat /etc/hosts
	curl http://$RMT_SERVER/tools/rmt-client-setup --output rmt-client-setup
	chmod +x rmt-client-setup
	./rmt-client-setup --yes --fingerprint $RMT_CERT_FINGERPRINT https://$RMT_SERVER/
	suseconnect -p sle-module-python3/15.5/x86_64
        suseconnect -p sle-module-public-cloud/15.5/x86_64
        ;;
    scc)
	REG_CODE=${REG_CODE:-123456789}
	SUSEConnect -r $REG_CODE
	suseconnect -p sle-module-python3/15.5/x86_64
	suseconnect -p sle-module-public-cloud/15.5/x86_64
        ;;
esac

