#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 1 ]; then
    set -x
fi
set -eu
set -o pipefail

[ -n "$ARCH" ]

if [ 'amd64' = "$ARCH" ] ; then
    ARCH="x86_64"
fi

zypper -n in kernel-default
zypper -n rm kernel-default-base

