#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 1 ]; then
    set -x
fi
set -eu
set -o pipefail

# Replace kernel-default-base with kernel-default to provide iscsi modules
zypper -n in kernel-default kernel-firmware-all
zypper -n rm kernel-default-base

