#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 1 ]; then
    set -x
fi
set -eu
set -o pipefail

[ -n "$ARCH" ]

if [ 'amd64' = "$ARCH" ] ; then
    ARCH="x86_64"
fi

zypper rr SLE-Product-SLES
zypper rr SLE-Module-Basesystem
zypper rr SLE-Module-Server-Applications
zypper rr SLE-Product-SLES-update
zypper rr SLE-Module-Basesystem-update
zypper rr SLE-Module-Server-Applications-update
rm -rf /etc/pki/trust/anchors/rmt.crt
update-ca-certificates

